[package]
name = "pneutype"
version = "0.5.0"
authors = ["Victor Dods <victor.dods@gmail.com>"]
edition = "2021"

[dependencies]
pneutype-derive = { path = "../pneutype-derive" }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
